name: Publish bottles
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Formula/*.rb'
      - '.github/workflows/publish.yml'
permissions:
  contents: write
jobs:
  upload:
    runs-on: macos-14
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Build bottles
        run: |
          brew tap ${{ github.repository }}
          brew test-bot --only-formulae --tap=${{ github.repository }} --root-url=https://github.com/${{ github.repository }}/releases/download/bottles --testing-formulae=libvirt,virt-manager,virt-viewer,gtk-vnc
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: bottles
          name: Homebrew bottles
          files: '*.bottle.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
